#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2024 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# Mail logfile to $MAILTO, then remove logfile.  The logfile is assumed to be
# the name of the specified script w/ .log at the end.
#

prog=$1
log=$prog.log
lock=$prog.lock

if [ -z "$MAILTO" ]; then
    echo "ERROR: \$MAILTO not set"
    exit 1
fi
if [ -z "$prog" ]; then
    echo "ERROR: program argument expected"
    exit 1
fi
if [ ! -f $prog ]; then
    echo "ERROR: no such file '$prog'"
    exit 1
fi
if [ ! -f $log ]; then
    echo "ERROR: '$log' doesn't exist"
    exit 1
fi

# wait for script to finish if running
while [ -f $lock ]; do
    sleep 1
done

# just do nothing if log missing or empty
if [ ! -s $log ]; then
    exit 0
fi

# rotate the logfile
#
# FIXME: This is definately not atomic.  A subsequent run could swoop in and
#        start writing to the logfile right now and mess things up...  We'd
#        better just make sure the program starts BEFORE we try to
#        mail-and-purge it's logfile (i.e., don't schedule both to happen on
#        the hour)
#
# NOTE: We copy and then truncate the logfile so that if anyone is tailing it,
#       they get a "file truncated" indication.
#
cp $log $log.sending
echo >$log

# mail the logfile
mail -s "awesome logfile from $(hostname): $(basename $prog)" $MAILTO -E 'set nonullbodymsg' --content-type=text/plain -A $log.sending </dev/null

# remove the logfile
rm $log.sending

exit 0
