#!/bin/bash
#
# script for generating periodic drbd status
#
# NOTE: All output appended to logfile, which is then mailed and removed each
#       night (log rotation and mailing is not this script's responsibility).
#

# parse our config
[ -f $0.conf ] && . $0.conf


log=$0.log
lock=$0.lock
stamp=$(date +"%Y-%m-%dT%H-%M-%S")

# FIXME: we can do better than this...
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
    dryrun="-n"
else
    dryrun=
    # when not dryrun, we redirect all output to the logfile
    exec 1>>$log
    exec 2>&1
fi

# make sure we're not already running
[ -e $lock ] && exit 0

# parse common stuff
. status-common


echo "--- START: $stamp ----------------------------------------------------"

touch $lock

case "$MODE" in
    analyze)
        # check for problems and append extra output
        echo "Doing end of day analysis"
        failures=0
        # disk states other than UpToDate
        check Diskless
        check Attaching
        check Detaching
        check Failed
        check Negotiating
        check Inconsistent
        check Outdated
        check DUnknown
        check Consistent
        # Roles other than Primary/Secondary
        check Unknown
        # Bad connection states
        check StandAlone
        check Disconnecting
        check Unconnected
        check Timeout
        check BrokenPipe
        check NetworkFailure
        check ProtocolError
        check TearDown
        check Connecting
        # Sync states
        check StartingSyncS
        check StartingSyncT
        check WFBitMapS
        check WFBitMapT
        check WFSyncUUID
        check SyncSource
        check SyncTarget
        check PausedSyncS
        check PausedSyncT
        check VerifyS
        check VerifyT
        check Ahead
        check Behind
        if [ $failures -ne 0 ]; then
            echo "!!!!"
            echo "!!!! Checks Failed: $failures"
            echo "!!!!"
        else
            echo "All checks passed.  :-)"
        fi
        ;;
    *)
        # append status
        drbdadm status
esac

echo "--- END: $stamp (at $(date +"%Y-%m-%dT%H-%M-%S")) -----------------------------"
rm -f $lock
exit 0
