#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2021 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# Start a gkrellm -s instance for a list of nodes with helpful groupings.
#

nodes_default="frodo sam merry gandalf srv-files aragorn"
nodes_dom0="frodo sam merry gandalf"
nodes_srv="srv-files srv-net srv-auth srv-www srv-router1 srv-router2"
nodes_dev="aragorn legolas gimli boromir"
nodes_home="gandalf elrond galadriel glorfindel"


usage()
{
    echo "usage: $(basename $0) [default|dom0|srv|dev|home]"
}


nodes=
while (($#)); do
    case $1 in
        dom0)
            nodes+=" $nodes_dom0"
            ;;
        srv)
            nodes+=" $nodes_srv"
            ;;
        dev)
            nodes+=" $nodes_dev"
            ;;
        home)
            nodes+=" $nodes_home"
            ;;
        default)
            nodes+=" $nodes_default"
            ;;
        *)
            usage
            exit 1
    esac
    shift
done
[ -n "$nodes" ] || nodes=$nodes_default


# remove duplicates
nodes=$(echo $nodes | tr ' ' '\n' | sort -u)

# remove local host
nodes=$(echo $nodes | sed "s|\<$(hostname)\>||")

echo nodes: $nodes
for n in $nodes; do
    gkrellm -s $n &!
    # w/out sleep, some of the windows end up only partially drawn...  1 second
    # seems to fix it.  let's try .1 and see if it works.
    sleep .1
done


exit 0


#
# old script from 2019 Nautilus season
#

data_nodes="shiphouse nautilusfs datalabfour camproc de-nuc"
inst_nodes="cam-acq-dev capture rovnav cam-acq1 argusgui hercgui"

# 1st, local gkrellm
go="gkrellm &!"
echo $go
eval $go

# now data_nodes, which we can reach directly
for x in $data_nodes; do
    go="gkrellm -s $x &!"
    echo $go
    eval $go
done

# and now inst_nodes, which we need to launch remotely via shiphouse
for x in $inst_nodes; do
    go="ssh -X michael@shiphouse gkrellm -s $x &!"
    echo $go
    eval $go
done
