#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2022 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# Start a gkrellm -s instance for a list of nodes with helpful groupings.
#

nodes_default="frodo sam merry gandalf srv-files aragorn"
nodes_dom0="frodo sam merry gandalf"
nodes_srv="srv-files srv-net srv-auth srv-www srv-router1 srv-router2 srv-files2"
nodes_dev="aragorn legolas gimli boromir jammydev"
nodes_home="gandalf elrond galadriel glorfindel haldir"
nodes_nautilus="coresrv1 coresrv2 netsrv1 nautilusfs copynuc dataproc"
nodes_nautilus_all="coresrv1 coresrv2 netsrv1 netsrv2 netsrv3 shiphouse nautilusfs capture rovnav argusgui hercgui copynuc rrnuc logger datalabfour datalabfive datarec dataxform netutil alleycat alleyrat de-nuc lilhercgui blame-nuc dataproc datalabsix"


usage()
{
    echo "usage: $(basename $0) [default|dom0|srv|dev|home|nautilus|nautilus_all]"
}


nodes=
while (($#)); do
    case $1 in
        dom0)
            nodes+=" $nodes_dom0"
            ;;
        srv)
            nodes+=" $nodes_srv"
            ;;
        dev)
            nodes+=" $nodes_dev"
            ;;
        home)
            nodes+=" $nodes_home"
            ;;
        nautilus)
            nodes+=" $nodes_nautilus"
            ;;
        nautilus_all)
            nodes+=" $nodes_nautilus_all"
            ;;
        default)
            nodes+=" $nodes_default"
            ;;
        *)
            usage
            exit 1
    esac
    shift
done
[ -n "$nodes" ] || nodes=$nodes_default


# remove duplicates
nodes=$(echo $nodes | tr ' ' '\n' | sort -u)

# remove local host
nodes=$(echo $nodes | sed "s|\<$(hostname)\>||")

echo nodes: $nodes
for n in $nodes; do
    gkrellm -s $n &!
    # w/out sleep, some of the windows end up only partially drawn...  1 second
    # seems to fix it, most of the time.  .2 seems to fix it all the time.
    sleep .2
done


exit 0
