#!/bin/sh -e
#
# Raise/Lower CAH WireGuard VPN when we raise an interface.
#

# if this interface wasn't our gw, don't do anything
gw=$(route -n | awk '/^0.0.0.0/ {print $NF}')
[ -n "$gw" -a "$gw" != "$1" ] && exit 0


case "$2" in
    up)
        echo starting cah-vpn
        /scrap/awesome-powers/net/cah-vpn start
        ;;
    down)
        echo stopping cah-vpn
        /scrap/awesome-powers/net/cah-vpn stop
        ;;
    *)
        echo "$0: called with unknown action \`$2'" 1>&2
        exit 0
        ;;
esac

exit 0
