#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2021 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around wg-vpn providing settings for the CAH VPN.
#

export DNS_IP=10.37.20.4
export DNS_SEARCH="cowesettanimalhospital.com"
export DNS_NAME=srv-net.cowesettanimalhospital.com
export INTERFACES="wg-cah1 wg-cah2"

exec $(dirname $0)/wg-vpn $*
