#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2022 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Cowesett Animal
# Hospital's 4g modem WAN interface.
#
#
### higher priority stuff
#
# voip - not currently on it's own vlan, but planning to switch that as soon as
# possible.  once i have, i can mark packets via iptables very easily.
#
# dicom - not nearly as important as the voip, but we could consider
# identifying dicom traffic going from the ultrasound machine or digital xray
# machine(s)...
#
### lower priority stuff
#
# anything coming from vlan100.
#
### middle tier
#
# anything else
#

export DEV=eth0.3
# FIXME: i have no idea what the up/down speeds are like on this... better test
#        it out.  i seem to remember it being pretty bad wherever i placed the
#        modem...  like 2M down, 1M up or something?
#
#        testing with antena on roof at home got about 8M down, 4M up... but
#        tests were all over the place.  strangest one was 6 down, 11 up.
#        perhaps more tweaking of the antena could see some gains, but it was
#        annoying working on the roof.  ;-)
#
# FIXME: did more testing from basement shelf at home.  The netgear w/out any
#        antena or dangly bits pulled in pretty consistent 4Mbps/4Mbps Down/Up.
#        The peplink was suprisingly not-quite-as-good (but is way more
#        featureful), but I think it will play much better with a non-crappy
#        antena.  Will need to do more testing when I put this into place at
#        the hospital.
#
# FIXME: The danger is setting UP_MB too high... if we do, we won't be able to
#        push enough traffic to get our tc rules to apply propperly.  But if we
#        set it too low, we'll also be capping what we CAN use...  hmm...
#
export UP_MBIT=4
export DOWN_MBIT=4

export UP_HIGH_GUARANTEED_RATE_KBIT=1024
export UP_MEDIUM_GUARANTEED_RATE_KBIT=1024
export UP_LOW_GUARANTEED_RATE_KBIT=8



exec $(dirname $0)/tc-rules $*
