#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2022 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Cowesett Animal
# Hospital's Cox Cable WAN interface.
#
#
### higher priority stuff
#
# voip - Not currently on it's own vlan, but planning to switch that as soon as
# possible.  once I have, I can mark packets via iptables very easily.  It
# looks like our phones are using DSCP: AF31, TOS: 0x68 (104 decimal), so I
# guess we could pick that traffic out.  For now, though, I've marked all
# traffic from our phones' MACs as high priority.
#
# dicom - Not nearly as important as the voip, but we could consider
# identifying dicom traffic going from the ultrasound machine or digital xray
# machine(s)...
#
### lower priority stuff
#
# anything coming from vlan100.
#
### middle tier
#
# anything else
#

export DEV=eth0.2
export UP_MBIT=20
export DOWN_MBIT=100

exec $(dirname $0)/tc-rules $*
