#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2024 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for Aragorn's dedicated
# ermgency backup 4G modem WAN interface at the Cowesett Animal Hospital.
# Unlike the other 4G modem interface on vlan3, this one is NOT shared with the
# rest of the hospital.
#
#
### higher priority stuff
#
# nothing (other than default tc-rules defaults)
#
### lower priority stuff
#
# nothing
#
### middle tier
#
# anything else
#

export DEV=xenbr0.4

export UP_MBIT=4
export DOWN_MBIT=4

exec $(dirname $0)/tc-rules $*
