#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2021 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Cowesett Animal
# Hospital's 4g modem WAN interface.
#
#
### higher priority stuff
#
# voip - not currently on it's own vlan, but planning to switch that as soon as
# possible.  once i have, i can mark packets via iptables very easily.
#
# dicom - not nearly as important as the voip, but we could consider
# identifying dicom traffic going from the ultrasound machine or digital xray
# machine(s)...
#
### lower priority stuff
#
# anything coming from vlan100.
#
### middle tier
#
# anything else
#

export DEV=eth0.3
# FIXME: i have no idea what the up/down speeds are like on this... better test
#        it out.  i seem to remember it being pretty bad wherever i placed the
#        modem...  like 2M down, 1M up or something?
#
export UP_MB=2.5
export DOWN_MB=4.5

exec $(dirname $0)/tc-rules $*
