#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2024 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Cox Cable WAN
# interface on srv-router2 at the Cowesett Animal Hospital.  This is a bit
# hairy, because we have srv-router1 acting as the gateway for the rest of the
# hospital (other than aragorn), and it's trying to do traffic shaping of it's
# own.  I don't really want to cap srv-router1's cable interface at 10M to
# really guarantee bandwidth for us, because that will slow down all our
# off-site backups considerably...  but that means we're essentually
# overcommitting the uplink.  To help prevent overruns, I'm going to heavily
# limit the uplink on aragorn and srv-router2 and lower the MEDIUM guarateed
# rate on srv-router1 a bit.
#
#
### higher priority stuff
#
# nothing (other than default tc-rules defaults)
#
### lower priority stuff
#
# nothing
#
### middle tier
#
# anything else
#

export DEV=eth0.2
export UP_MBIT=5
export DOWN_MBIT=100

exec $(dirname $0)/tc-rules $*
