#!/bin/bash
#
# This script wraps around wg-vpn providing settings for the CAH VPN
#

export DNS_IP=10.42.20.1
export DNS_SEARCH="labriola.dyndns.org"
export DNS_NAME=elrond.labriola.dyndns.org
export INTERFACES="wg-labriola1"

exec $(dirname $0)/wg-vpn $*
