#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2024 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Cowesett Animal
# Hospital's Cox Cable WAN interface.
#
#
### higher priority stuff
#
# voip - At home, we have an ancient vonage device.  I'll mark it by mac in
# iptables.
#
### lower priority stuff
#
# blacklisted devices (via iptables marking), perhaps anything coming from
# vlan100 (if i ever split that out)?
#
### middle tier
#
# anything else
#

export DEV=eth0.2
export UP_MBIT=20
export DOWN_MBIT=100

exec $(dirname $0)/tc-rules $*
