#!/bin/bash

showit()
{
    echo "# $*"
    eval $*
    echo
}


start()
{
    showit route add -net 10.1.0.0/16 gw 10.1.20.1
}


stop()
{
    showit route del -net 10.1.0.0/16 gw 10.1.20.1
}


case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    status)
        showit route
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
