#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2021 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script tweaks the secondary router.  Seems a little odd, but we've got 2
# scripts/services, make-primary and make-secondary.  Basically, you're either
# a primary router, a secpondary router, or NOT a rounter (in which case you
# don't do either).  There are a bunch of hardcoded things in here, so edit
# before use.
#


showit()
{
    echo "# $*"
    eval $*
    echo
}


start()
{
    showit route add -net 10.37.0.0/16 gw 10.37.20.1
}


stop()
{
    showit route del -net 10.37.0.0/16 gw 10.37.20.1
}


case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    status)
        showit route
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
