#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2021 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script promotes/demotes the primary router.  Seems a little odd, but
# we've got 2 scripts/services, make-primary and make-secondary.  Basically,
# you're either a primary router, a secpondary router, or NOT a rounter (in
# which case you don't do either).  There are a bunch of hardcoded things in
# here, so edit before use.
#

# interfaces
vlans="10 20 30 40"


doit()
{
    case $1 in
        up)
            ipaddr="ip addr add"
            wgcmd="up"
            ;;
        down)
            ipaddr="ip addr del"
            wgcmd="down"
            ;;
        *)
            echo "invalid usage"
            exit 1
            ;;
    esac

    # add/remove the .1 address to/from all vlan interfaces
    for x in $vlans; do
        go="$ipaddr 10.37.$x.1/24 dev eth0.$x"
        echo $go
        eval $go
    done

    # raise/lower wg-cah (our VPN)
    go="wg-quick $wgcmd wg-cah"
    echo $go
    eval $go
    
    # raise/lower wg-labriola (VPN to labriola)
    #go="wg-quick $wgcmd wg-labriola"
    #echo $go
    #eval $go
    
    # anything else?
}


showit()
{
    echo "# $*"
    eval $*
    echo
}


case $1 in
    start)
        doit up
        ;;
    stop)
        doit down
        ;;
    restart)
        doit down
        sleep 1
        doit up
        ;;
    status)
        showit wg show
        if [ "$(wg show | wc -l)" != 0 ]; then
            showit ip addr show
            showit route
	fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
