#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2021 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Nautilus
# 4g-modem WAN interface.
#
#
### higher priority stuff
#
# Traffic coming from vlan4 (voip tunnel) and vlan96 (encoders) is marked as
# HIGH priority by iptables.
#
### lower priority stuff
#
# Traffic coming from vlan100 (public) is marked as LOW priority by iptables.
# The unifi manager is also used to limit the wifi for us.
#
### middle tier
#
# Everything else.  This includes normal operational stuff on the instrument
# and data networks, as well as Interactions/Outreach and occasional giant
# google drive uploads (unless the machine is marked LOW priority in iptables).
#

export DEV=eth0.7
# FIXME: Well, this is really going to depend on where we are and what we're
#        connected to...  let's stick 10 up/down in here as a random shot in
#        the dark...
export UP_MB=10
export DOWN_MB=10

exec $(dirname $0)/tc-rules $*
