#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2021 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Nautilus
# Comtech WAN interface.
#
#
### higher priority stuff
#
# Traffic coming from vlan4 (voip tunnel) and vlan96 (encoders) is marked as
# HIGH priority by iptables.
#
### lower priority stuff
#
# Traffic coming from vlan100 (public) is marked as LOW priority by iptables.
# The unifi manager is also used to limit the wifi for us.
#
### middle tier
#
# Everything else.  This includes normal operational stuff on the instrument
# and data networks, as well as Interactions/Outreach and occasional giant
# google drive uploads.
#

# FIXME: Video/Voip is more important than outreach (i.e., NautilusLive video
#        won't stop if we run out of bandwidth during an Interaction), and
#        outreach is more important than Joe Sailor doing a video call when he
#        shouldn't be.  That makes sense... but what about giant google drive
#        uploads from data network or production macs?  Those could starve an
#        Interaction of bandwidth... should we try and classify those as low
#        priority?  We could accomplish that by telling staff to only do giant
#        uploads from public network...  have to work through the actual
#        workflow for this.

export DEV=eth0.95
# FIXME: If this is being used for vlan95 while we're using the newtec modems,
#        we need to tweak this.  The newtec setup gives us 20 up/down, but
#        really we split it accross two vlan interfaces.  Vlan3 is for basic
#        internet traffic, and vlan95 is for video back to URI.
#
export UP_MB=13
export DOWN_MB=9
#
# NOTE: The newtec's give us 20 mbit up/down, but we split it between vlan95
#       and vlan3.  Combined, they cannot exceed 20.  Keep them in sync!
#
#export UP_MB=10
#export DOWN_MB=2

exec $(dirname $0)/tc-rules $*
