#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2022 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around tc-rules providing settings for the Nautilus Newtec
# WAN interface.
#
#
### higher priority stuff
#
# voip - originates on vlan2095, then gets tunneled through vlan4, which
# eventualy sends the packets out whatever WAN interface is my gateway.  so,
# how can we classify that traffic once it's in the queue for vlan3, for
# example?  i can mark packets that originate from vlan2095 in iptables... but
# will I be able to see that once the packets are encapsulated by the
# voip-tunnel device?
#
# hmm... instead of vlan tags, we can match on ip address/netmask... except
# it's going to be after NAT happens... so we would have to fwmark in iptables
# all the traffic coming from vlan2095, then match on the mark in the tc
# filter.  i think the fwmark will remain, even after all the voip-tunnel
# shenanigans... will have to test it.
#
# could also try and identify voip via the destination address and/or port...
#
# After talking to Rachel, it sounds like we won't be able to clasify the voip
# traffic by vlan, because the traffic is encapsulated in the voip-tunnel in
# such a way that we can't see that info.
#
# voip:  131.128.101.42 udp 22
# vlink: 131.128.101.43 udp 22
#
# I could also just prioritize everything coming over the vlan4 tunnel, which
# should only be important stuff anyways.
#
# video - originates on vlan96, goes out vlan95 to URI if available, otherwise
# goes out normal WAN interface.  i can mark vlan96 packates in iptables.
#
# again, could try to identify destination address and/or port...
#
# Could look at the TOS field set by the encoders (and controlled via their web
# gui).
#
# outreach stuff - all this traffic should originate from the studio in the
# van, from one or both of the mac mini's in there.  studio mac and playback
# mac, I think.  We could just prioritize any traffic coming from those 2 IPs.
#
### lower priority stuff
#
# anything coming from vlan100.  the unifi manager can limit the wifi for us,
# but we should further limit it w/ tc rules
#
# any other traffic we can identify and mark in iptables
#
### middle tier
#
# anything else.  could consider letting the studio interaction stuff fall in
# here... that would prioritize it below the voip, vlink, and encoders, but
# above random joe watching youtube on the public network.
#

export DEV=eth0.3
# NOTE: The newtec's give us 20 mbit up/down, but we split it between vlan95
#       and vlan3.  Combined, they cannot exceed 20.  Keep them in sync!
export UP_MB=10
export DOWN_MB=18

exec $(dirname $0)/tc-rules $*
