#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2024 Michael D Labriola <veggiemike@sourceruckus.org>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# This script wraps around wg-vpn providing settings for the Source Ruckus VPN.
#

export DNS_IP=10.99.0.1
export DNS_SEARCH="vpn.sourceruckus.org"
export DNS_NAME=ruckus-vpn.vpn.sourceruckus.org
export INTERFACES="wg-ruckus"

exec $(dirname $0)/wg-vpn $*
