#!/bin/bash

while [ $# -gt 0 ]; do
    timeout=15
    while [ $timeout -gt 0 ]; do
        ping -c1 -W1 $1 && break
        sleep 1
        timeout=$((timeout-1))
    done
    if [ $timeout -eq 0 ]; then
        echo "Waiting for $1 failed after 15 seconds!"
        exit 1
    fi
    shift
done

exit 0
