#!/bin/bash
#
# Awesome Powers - scripts & config files of pure awesomeness
#
# Copyright 2018-2021 Michael D Labriola <michael.d.labriola@gmail.com>
#
# Licensed under the GPLv3. See the file COPYING for details. 
#
# Simple script that waits for a specified list of hosts to be reachable on the
# network before returning (unless the timeout is reached).  Helpful for
# syncronizing nodes during bootup with systemd rules.
#

while [ $# -gt 0 ]; do
    timeout=15
    while [ $timeout -gt 0 ]; do
        ping -c1 -W1 $1 && break
        sleep 1
        timeout=$((timeout-1))
    done
    if [ $timeout -eq 0 ]; then
        echo "Waiting for $1 failed after 15 seconds!"
        exit 1
    fi
    shift
done

exit 0
